Repository scm-manager/scm-manager, pull requests merged in 2020-08, with the labels that each got.

#1275 adds documentation for importing existing repositories
  docs/en/faq.md
  docs/en/import.md
  docs/en/navigation.yml
Labels: documentation

#1277 repository name may not end with ".git" extension
  CHANGELOG.md
  scm-ui/ui-webapp/src/repos/components/form/repositoryValidation.test.ts
  scm-ui/ui-webapp/src/repos/components/form/repositoryValidation.ts
Labels: bug

#1286 ".git" extension not allowed on the end of repository name
  scm-core/src/main/java/sonia/scm/util/ValidationUtil.java
  scm-core/src/test/java/sonia/scm/util/ValidationUtilTest.java
Labels: bug

#1287 Add preselected value to options in DropDown if missing
  CHANGELOG.md
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/forms/DropDown.stories.tsx
  scm-ui/ui-components/src/forms/DropDown.tsx
Labels: bug

#1289 show error and helpful message if plugin loading failed
  CHANGELOG.md
  scm-ui/ui-webapp/src/containers/PluginLoader.tsx
Labels: bug

#1290 fix timing problem with anchor links on markdown view
  CHANGELOG.md
  scm-ui/ui-components/src/MarkdownView.tsx
Labels: bug

#1301 Execute e2e cypress tests as part of integration tests
  Jenkinsfile
  build/Dockerfile
  build/Makefile
  package.json
  scm-it/pom.xml
  scm-ui/e2e-tests/cypress.json
  scm-ui/e2e-tests/cypress/.gitignore
  scm-ui/e2e-tests/package.json
  scm-ui/e2e-tests/src/index.js
  scm-ui/ui-components/src/devBuild.test.ts
  scm-ui/ui-components/src/devBuild.ts
  scm-ui/ui-scripts/src/webpack.config.js
  scm-ui/ui-webapp/public/index.mustache
  scm-webapp/src/main/java/sonia/scm/TemplatingPushStateDispatcher.java
  scm-webapp/src/test/java/sonia/scm/PushStateDispatcherProviderTest.java
  scm-webapp/src/test/java/sonia/scm/TemplatingPushStateDispatcherTest.java
  yarn.lock
Labels: enhancement

#1300 Fix plugin dependency installation error
  CHANGELOG.md
  scm-webapp/src/main/java/sonia/scm/plugin/DefaultPluginManager.java
  scm-webapp/src/test/java/sonia/scm/plugin/DefaultPluginManagerTest.java
Labels: bug

#1303 Fix broken markdown rendering
  CHANGELOG.md
  scm-ui/ui-components/src/MarkdownView.tsx
Labels: bug

#1306 Fix detection of markdown files for files having content does not sta…
  CHANGELOG.md
  scm-ui/ui-webapp/src/repos/sources/containers/SourcesView.tsx
  scm-webapp/pom.xml
  scm-webapp/src/main/java/sonia/scm/api/v2/ContentTypeResolver.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ContentResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/DiffResultToDiffResultDtoMapper.java
  scm-webapp/src/test/java/sonia/scm/api/v2/ContentTypeResolverTest.java
Labels: bug
