Repository scm-manager/scm-manager, pull requests merged in 2020-12, with the labels that each got.

#1457 Fixed unexpected mercurial server pool stop
  CHANGELOG.md
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/DefaultChangesetToChangesetDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/TagCollectionToDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/TagDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/TagToTagDtoMapper.java
Labels: bug

#1463 Feature/import hg from url
  CHANGELOG.md
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgCommandContext.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgPullCommand.java
Labels: enhancement

#1461 Prepare dependency management for gradle plugins
  pom.xml
Labels: dependencies

#1462 Move plugin build modules to external repositories
  package.json
  scm-ui/babel-preset/index.js
  scm-ui/babel-preset/package.json
  scm-ui/eslint-config/package.json
  scm-ui/eslint-config/src/__resources__/AllowRootImport.tsx
  scm-ui/eslint-config/src/__resources__/AvoidSourceImport.tsx
  scm-ui/eslint-config/src/__resources__/Node.js
  scm-ui/eslint-config/src/__resources__/Typescript.ts
  scm-ui/eslint-config/src/__resources__/TypescriptWithJsx.tsx
  scm-ui/eslint-config/src/index.js
  scm-ui/eslint-config/src/index.test.js
  scm-ui/jest-preset/jest-preset.js
  scm-ui/jest-preset/package.json
  scm-ui/jest-preset/src/__mocks__/fileMock.js
  scm-ui/jest-preset/src/__mocks__/styleMock.js
  scm-ui/jest-preset/src/__mocks__/workerMock.js
  scm-ui/jest-preset/src/findName.js
  scm-ui/jest-preset/src/findTarget.js
  scm-ui/jest-preset/src/index.js
  scm-ui/jest-preset/src/setup.js
  scm-ui/prettier-config/index.js
  scm-ui/prettier-config/package.json
  scm-ui/tsconfig/package.json
  scm-ui/tsconfig/tsconfig.json
  scm-ui/ui-components/package.json
  scm-ui/ui-extensions/package.json
  scm-ui/ui-plugins/package.json
  scm-ui/ui-scripts/package.json
  scm-ui/ui-styles/package.json
  yarn.lock
Labels: dependencies

#1472 support permalinks to lines in source code view
  CHANGELOG.md
  scm-ui/ui-components/src/CopyToClipboard.ts
  scm-ui/ui-components/src/SyntaxHighlighter.stories.tsx
  scm-ui/ui-components/src/SyntaxHighlighter.tsx
  scm-ui/ui-components/src/SyntaxHighlighterRenderer.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/sources/components/content/SourcecodeViewer.tsx
Labels: enhancement

#1473 Downgrade Jenkins JDK version to Java 8
  Jenkinsfile
  build/Dockerfile
  build/Makefile
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/BranchRootResourceTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/TagRootResourceTest.java
  scm-webapp/src/test/java/sonia/scm/security/AuthorizationChangedEventProducerTest.java
Labels: bug

#1471 Feature/import svn from dump
  CHANGELOG.md
  scm-core/src/main/java/sonia/scm/repository/spi/UnbundleCommandRequest.java
  scm-ui/ui-components/src/forms/FileUpload.tsx
  scm-ui/ui-components/src/forms/index.ts
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/components/ImportFromBundleForm.tsx
  scm-ui/ui-webapp/src/repos/components/ImportRepositoryFromBundle.tsx
  scm-ui/ui-webapp/src/repos/containers/ImportRepository.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryImportResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryTypeToRepositoryTypeDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ResourceLinks.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/RepositoryRootResourceTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/RepositoryTypeToRepositoryTypeDtoMapperTest.java
  scm-webapp/src/test/resources/sonia/scm/api/v2/svn.dump
  scm-webapp/src/test/resources/sonia/scm/api/v2/svn.dump.gz
Labels: enhancement

#1474 Update @scm-manager/jest-preset to v2.12.1
  scm-ui/ui-components/package.json
  scm-ui/ui-extensions/package.json
  scm-ui/ui-plugins/package.json
  scm-ui/ui-webapp/package.json
  yarn.lock
Labels: enhancement

#1476 Namespace filter leads to empty page
  CHANGELOG.md
  scm-ui/ui-webapp/src/repos/containers/Overview.tsx
  scm-ui/ui-webapp/src/repos/modules/repos.ts
Labels: bug

#1479 Fix tooltip arrow height in firefox
  CHANGELOG.md
  scm-ui/ui-styles/src/scm.scss
Labels: bug

#1480 Fix accidentally blocked requests with non ascii characters
  CHANGELOG.md
  scm-webapp/src/main/java/sonia/scm/lifecycle/modules/ScmSecurityModule.java
Labels: bug

#1483 Fix unit tests on Java 11
  Jenkinsfile
  build/Dockerfile
  build/Makefile
  pom.xml
  scm-webapp/src/main/java/sonia/scm/web/i18n/I18nServlet.java
  scm-webapp/src/test/java/sonia/scm/plugin/MultiParentClassLoaderTest.java
  scm-webapp/src/test/java/sonia/scm/web/i18n/I18nServletTest.java
Labels: bug
