Repository scm-manager/scm-manager, pull requests merged in 2020-06, with the labels that each got.

#1174 pickup system property to configure jetty host
  CHANGELOG.md
  scm-packaging/deb/src/main/fs/etc/scm/server-config.xml
  scm-packaging/docker/src/main/fs/etc/scm/server-config.xml
  scm-packaging/rpm/src/main/fs/etc/scm/server-config.xml
  scm-packaging/unix/src/main/fs/conf/server-config.xml
  scm-packaging/windows/src/main/fs/conf/server-config.xml
Labels: bug

#1175 Added option to configure jvm parameter of docker image
  CHANGELOG.md
  docs/en/installation/docker.md
  scm-packaging/docker/Dockerfile
  scm-packaging/docker/src/main/fs/opt/scm-server/bin/scm-server
Labels: documentation, enhancement

#1176 avoid caching of detected browser language
  CHANGELOG.md
  scm-ui/ui-webapp/src/i18n.ts
Labels: bug

#1187 improve eslint config
  package.json
  scm-ui/eslint-config/package.json
  scm-ui/eslint-config/src/__resources__/AllowRootImport.tsx
  scm-ui/eslint-config/src/__resources__/AvoidSourceImport.tsx
  scm-ui/eslint-config/src/__resources__/Node.js
  scm-ui/eslint-config/src/__resources__/Typescript.ts
  scm-ui/eslint-config/src/__resources__/TypescriptWithJsx.tsx
  scm-ui/eslint-config/src/index.js
  scm-ui/eslint-config/src/index.test.js
  yarn.lock
Labels: enhancement

#1202 remove wait for sonarqube qualitygate
  Jenkinsfile
Labels: enhancement

#1200 find single changeset for shortened changesetId
  scm-ui/ui-webapp/src/repos/modules/changesets.ts
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ChangesetRootResource.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/ChangesetRootResourceTest.java
Labels: enhancement

#1201 Mind custom directories for repository types in migration
  CHANGELOG.md
  scm-webapp/src/main/java/sonia/scm/update/repository/BaseMigrationStrategy.java
  scm-webapp/src/main/java/sonia/scm/update/repository/V1RepositoryMigrationLocationResolver.java
  scm-webapp/src/main/java/sonia/scm/update/repository/V1RepositoryTypeConfig.java
  scm-webapp/src/test/java/sonia/scm/update/repository/V1RepositoryMigrationLocationResolverTest.java
  scm-webapp/src/test/resources/sonia/scm/update/repository/scm-home.v1.zip
Labels: bug

#1203 fixes refetching loop for non existing changesets
  CHANGELOG.md
  scm-ui/ui-webapp/src/repos/containers/ChangesetView.tsx
Labels: bug

#1209 wait until recommended java installation is available for deb packages
  CHANGELOG.md
  scm-packaging/deb/src/main/deb/control/postinst
Labels: bug

#1208 #1195 do not force java home of recommended java dependency
  CHANGELOG.md
  scm-packaging/deb/src/main/fs/etc/default/scm-server
  scm-packaging/rpm/src/main/fs/etc/default/scm-server
Labels: bug

#1217 fix installation of debian packages on distros without preinstalled "at"
  CHANGELOG.md
  scm-packaging/deb/src/main/deb/control/postinst
Labels: bug

#1221 fixes broken migration with an empty security.xml
  CHANGELOG.md
  scm-webapp/src/main/java/sonia/scm/update/security/XmlSecurityV1UpdateStep.java
  scm-webapp/src/test/java/sonia/scm/update/security/XmlSecurityV1UpdateStepTest.java
  scm-webapp/src/test/resources/sonia/scm/update/security/emptySecurityV1.xml
Labels: bug
