Repository scm-manager/scm-manager, pull requests merged in 2020-07, with the labels that each got.

#1230 adds missing architecture to debian installation documentation
  CHANGELOG.md
  docs/en/installation/debian.md
Labels: bug, documentation

#1227 Fixes restart on deb or rpm installations
  CHANGELOG.md
  scm-packaging/deb/pom.xml
  scm-packaging/deb/src/main/bin/scm-server
  scm-packaging/deb/src/main/deb/control/postinst
  scm-packaging/deb/src/main/fs/etc/default/scm-server
  scm-packaging/deb/src/main/fs/etc/scm/logging.xml
  scm-packaging/deb/src/main/fs/etc/systemd/system/scm-server.service
  scm-packaging/rpm/pom.xml
  scm-packaging/rpm/src/main/bin/scm-server
  scm-packaging/rpm/src/main/fs/etc/default/scm-server
  scm-packaging/rpm/src/main/fs/etc/scm/logging.xml
  scm-packaging/rpm/src/main/fs/etc/systemd/system/scm-server.service
  scm-packaging/rpm/src/main/scripts/after-installation.sh
Labels: bug

#1229 update project metadata in order to fix deb and rpm package information
  CHANGELOG.md
  README.md
  pom.xml
  scm-packaging/deb/pom.xml
  scm-packaging/deb/src/main/deb/control/control
  scm-packaging/rpm/pom.xml
Labels: enhancement

#1232 Support for mercurial on python 3
  CHANGELOG.md
  scm-packaging/docker/Dockerfile
  scm-plugins/scm-hg-plugin/pom.xml
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/autoconfig/AutoConfigurator.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/autoconfig/PosixAutoConfigurator.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/installer/MacOSHgInstaller.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/installer/UnixHgInstaller.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/HgPythonScript.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/HgRepositoryHandler.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgBlameCommand.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgBranchesCommand.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgTagsCommand.java
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/hg/ext/fileview.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/blame.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/changelog.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/filelog.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/hgweb.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/log.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/scmhooks.py
  scm-plugins/scm-hg-plugin/src/main/resources/sonia/scm/python/util.py
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/autoconfig/PosixAutoConfiguratorTest.java
Labels: bug

#1234 Adds missing content type header to migration wizard
  CHANGELOG.md
  scm-webapp/src/main/java/sonia/scm/update/MigrationWizardServlet.java
Labels: bug

#1233 Update required plugins if available on plugin update
  CHANGELOG.md
  scm-ui/ui-webapp/public/locales/de/admin.json
  scm-ui/ui-webapp/public/locales/en/admin.json
  scm-webapp/src/main/java/sonia/scm/plugin/DefaultPluginManager.java
  scm-webapp/src/test/java/sonia/scm/plugin/DefaultPluginManagerTest.java
  scm-webapp/src/test/java/sonia/scm/plugin/PluginTestHelper.java
Labels: enhancement

#1242 fixes wrong cache directory location on windows
  CHANGELOG.md
  scm-packaging/windows/src/main/assembly/scm-server-app.xml
  scm-packaging/windows/src/main/fs/conf/server-config.xml
  scm-packaging/windows/src/main/fs/webapp/docroot/index.html
Labels: bug

#1244 Fixes NullPointerException in update steps
  CHANGELOG.md
  scm-core/src/main/java/sonia/scm/update/V1Properties.java
  scm-dao-xml/src/test/java/sonia/scm/update/xml/XmlV1PropertyDAOTest.java
Labels: bug

#1251 add jexl parser to parse expressions in urls
  CHANGELOG.md
  scm-core/pom.xml
  scm-core/src/main/java/sonia/scm/util/JexlUrlExpression.java
  scm-core/src/main/java/sonia/scm/util/JexlUrlParser.java
  scm-core/src/main/java/sonia/scm/web/data/EncodedStringList.java
  scm-core/src/main/java/sonia/scm/web/data/Encoder.java
  scm-core/src/main/java/sonia/scm/web/data/ImmutableEncodedChangeset.java
  scm-core/src/main/java/sonia/scm/web/data/ImmutableEncodedModifications.java
  scm-core/src/main/java/sonia/scm/web/data/ImmutableEncodedPerson.java
  scm-core/src/main/java/sonia/scm/web/data/ImmutableEncodedRepository.java
  scm-core/src/test/java/sonia/scm/util/JexlUrlParserTest.java
Labels: enhancement

#1256 ignore ports on proxy exclusions
  CHANGELOG.md
  scm-core/src/main/java/sonia/scm/net/Proxies.java
  scm-core/src/test/java/sonia/scm/net/ProxiesTest.java
Labels: bug

#1260 Feature/update optional dependencies
  CHANGELOG.md
  pom.xml
  scm-core/src/main/java/sonia/scm/plugin/AvailablePluginDescriptor.java
  scm-core/src/main/java/sonia/scm/plugin/InstalledPluginDescriptor.java
  scm-core/src/main/java/sonia/scm/plugin/PluginDescriptor.java
  scm-ui/ui-types/src/Plugin.ts
  scm-ui/ui-webapp/public/locales/de/admin.json
  scm-ui/ui-webapp/public/locales/en/admin.json
  scm-ui/ui-webapp/src/admin/plugins/components/PluginModal.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/PluginDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/PluginDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/plugin/DefaultPluginManager.java
  scm-webapp/src/main/java/sonia/scm/plugin/PluginCenterDto.java
  scm-webapp/src/main/java/sonia/scm/plugin/PluginCenterDtoMapper.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/PluginDtoMapperTest.java
  scm-webapp/src/test/java/sonia/scm/plugin/DefaultPluginManagerTest.java
  scm-webapp/src/test/java/sonia/scm/plugin/PluginCenterDtoMapperTest.java
Labels: enhancement

#1261 Invalidate branches cache synchronously on create new branch
  CHANGELOG.md
  scm-core/src/main/java/sonia/scm/repository/BranchCreatedEvent.java
  scm-core/src/main/java/sonia/scm/repository/api/RepositoryServiceFactory.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitBranchCommand.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitBranchCommandTest.java
Labels: bug

#1259 init svn repositories with README.md in trunk folder
  CHANGELOG.md
  docs/de/user/repo/index.md
  docs/en/user/repo/index.md
  scm-core/src/main/java/sonia/scm/repository/api/ModifyCommandBuilder.java
  scm-core/src/main/java/sonia/scm/repository/spi/ModifyCommandRequest.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/repository/spi/SvnModifyCommand.java
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/repository/spi/SvnModifyCommandTest.java
  scm-webapp/src/main/java/sonia/scm/repository/RepositoryInitializer.java
Labels: enhancement

#1262 updates reverse proxy documentation
  docs/en/administration/reverse-proxies.md
Labels: documentation

#1264 Feature/ssl configuration
  docs/en/administration/scm-server-ssl.md
  docs/en/administration/scm-server.md
  docs/en/navigation.yml
  scm-packaging/deb/pom.xml
  scm-packaging/deb/src/main/fs/etc/scm/server-config.xml
  scm-packaging/docker/pom.xml
  scm-packaging/docker/src/main/fs/etc/scm/server-config.xml
  scm-packaging/pom.xml
  scm-packaging/rpm/pom.xml
  scm-packaging/rpm/src/main/fs/etc/scm/server-config.xml
  scm-packaging/unix/pom.xml
  scm-packaging/unix/src/main/assembly/scm-server-app.xml
  scm-packaging/unix/src/main/fs/conf/server-config.xml
  scm-packaging/windows/src/main/assembly/scm-server-app.xml
  scm-packaging/windows/src/main/fs/conf/server-config.xml
Labels: documentation
