Repository scm-manager/scm-manager, pull requests merged in 2020-05, with the labels that each got.

#1114 Add class to manually validate rest data transfer
  CHANGELOG.md
  scm-core/pom.xml
  scm-core/src/main/java/sonia/scm/web/api/DtoValidator.java
  scm-core/src/test/java/sonia/scm/web/api/DtoValidatorTest.java
  scm-core/src/test/resources/META-INF/validation.xml
  scm-webapp/src/main/java/sonia/scm/api/v2/JavaxValidationExceptionMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ResteasyViolationExceptionToErrorDtoMapper.java
Labels: enhancement

#1129 Fix error with redundant line breaks
  CHANGELOG.md
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitHunkParser.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitHunkParserTest.java
Labels: bug

#1128 Validate subversion client checksums
  CHANGELOG.md
  pom.xml
Labels: bug

#1133 Fix permission check
  scm-core/src/main/java/sonia/scm/repository/api/RepositoryServiceFactory.java
  scm-core/src/test/java/sonia/scm/repository/api/RepositoryServiceFactoryTest.java
Labels: bug

#1107 add guide to prevent common pitfalls in ui development
  CHANGELOG.md
  docs/en/development/ui-common-pitfall.md
  docs/en/navigation.yml
Labels: documentation

#1148 Feature/sonar pr analysis
  Jenkinsfile
Labels: enhancement

#1158 Feature/sonar exclude frontend tests
  Jenkinsfile
Labels: bug

#1163 increase sonarqube timeout to 10 minutes
  Jenkinsfile
Labels: bug

#1164 Let build break on duplicates in classpath
  scm-webapp/pom.xml
Labels: enhancement

#1111 Added ClassLoader and Adapter parameters to typed store api
  CHANGELOG.md
  scm-core/pom.xml
  scm-core/src/main/java/sonia/scm/store/BlobStoreFactory.java
  scm-core/src/main/java/sonia/scm/store/ConfigurationEntryStore.java
  scm-core/src/main/java/sonia/scm/store/ConfigurationEntryStoreFactory.java
  scm-core/src/main/java/sonia/scm/store/ConfigurationStoreFactory.java
  scm-core/src/main/java/sonia/scm/store/DataStoreFactory.java
  scm-core/src/main/java/sonia/scm/store/StoreParameters.java
  scm-core/src/main/java/sonia/scm/store/StoreParametersBuilder.java
  scm-core/src/main/java/sonia/scm/store/TypedStoreParameters.java
  scm-core/src/main/java/sonia/scm/store/TypedStoreParametersBuilder.java
  scm-core/src/main/java/sonia/scm/store/TypedStoreParametersImpl.java
  scm-dao-xml/pom.xml
  scm-dao-xml/src/main/java/sonia/scm/store/JAXBConfigurationEntryStore.java
  scm-dao-xml/src/main/java/sonia/scm/store/JAXBConfigurationEntryStoreFactory.java
  scm-dao-xml/src/main/java/sonia/scm/store/JAXBConfigurationStore.java
  scm-dao-xml/src/main/java/sonia/scm/store/JAXBConfigurationStoreFactory.java
  scm-dao-xml/src/main/java/sonia/scm/store/JAXBDataStore.java
  scm-dao-xml/src/main/java/sonia/scm/store/JAXBDataStoreFactory.java
  scm-dao-xml/src/main/java/sonia/scm/store/TypedStoreContext.java
  scm-dao-xml/src/test/java/sonia/scm/store/JAXBDataStoreTest.java
  scm-dao-xml/src/test/java/sonia/scm/store/TypedStoreContextTest.java
  scm-test/src/main/java/sonia/scm/store/ConfigurationEntryStoreTestBase.java
  scm-test/src/main/java/sonia/scm/store/InMemoryConfigurationEntryStore.java
Labels: do not merge, enhancement
