Repository scm-manager/scm-manager, pull requests merged in 2021-02, with the labels that each got.

#1515 Fix permission check on branch deletion
  gradle/changelog/delete_branches_permission.yaml
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/BranchToBranchDtoMapper.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/BranchToBranchDtoMapperTest.java
Labels: bug

#1514 Update release process
  docs/en/release-process.md
Labels: documentation

#1517 Implement new changelog process
  build.gradle
  docs/en/release-process.md
  gradle/changelog/new_changelog_process.yaml
Labels: documentation, enhancement

#1516 Add architecture overview documentation
  docs/en/development/architecture-overview.md
Labels: documentation

#1528 Reduce time spend in configuration phase
  Jenkinsfile
  README.md
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: enhancement

#1532 Fix broken mercurial http post args configuration
  gradle/changelog/fix_hg_httppostargs.yaml
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/DefaultHgEnvironmentBuilder.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/web/HgCGIServlet.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/DefaultHgEnvironmentBuilderTest.java
Labels: bug, regression

#1541 Do not resolve external groups for system accounts
  gradle/changelog/fix_group_collector.yaml
  scm-core/src/main/java/sonia/scm/SCMContext.java
  scm-core/src/main/java/sonia/scm/security/Authentications.java
  scm-webapp/src/main/java/sonia/scm/group/DefaultGroupCollector.java
  scm-webapp/src/main/java/sonia/scm/web/security/AdministrationContextRealm.java
  scm-webapp/src/main/java/sonia/scm/web/security/DefaultAdministrationContext.java
  scm-webapp/src/main/resources/sonia/scm/web/security/system-account.xml
  scm-webapp/src/test/java/sonia/scm/group/DefaultGroupCollectorTest.java
  scm-webapp/src/test/java/sonia/scm/web/security/DefaultAdministrationContextTest.java
Labels: bug

#1538 Change file order inside repository archive
  gradle/changelog/change_import_export_order.yaml
  scm-webapp/src/main/java/sonia/scm/importexport/EnvironmentCheckStep.java
  scm-webapp/src/main/java/sonia/scm/importexport/FullScmRepositoryExporter.java
  scm-webapp/src/main/java/sonia/scm/importexport/FullScmRepositoryImporter.java
  scm-webapp/src/main/java/sonia/scm/importexport/ImportState.java
  scm-webapp/src/main/java/sonia/scm/importexport/ImportStep.java
  scm-webapp/src/main/java/sonia/scm/importexport/MetadataImportStep.java
  scm-webapp/src/main/java/sonia/scm/importexport/NoneClosingInputStream.java
  scm-webapp/src/main/java/sonia/scm/importexport/RepositoryImportStep.java
  scm-webapp/src/main/java/sonia/scm/importexport/StoreImportStep.java
  scm-webapp/src/main/java/sonia/scm/importexport/TarArchiveRepositoryStoreImporter.java
  scm-webapp/src/test/java/sonia/scm/importexport/FullScmRepositoryImporterTest.java
  scm-webapp/src/test/resources/sonia/scm/repository/import/scm-import-stores-before-repository.tar.gz
Labels: enhancement

#1535 Fix filter redirect on paginated overview page
  gradle/changelog/filter_on_pagination.yaml
  scm-ui/ui-components/src/OverviewPageActions.tsx
Labels: bug

#1540 Improve cache api for usage in plugins
  gradle/changelog/cache_improvement.yaml
  scm-core/src/main/java/sonia/scm/cache/Cache.java
  scm-core/src/main/java/sonia/scm/cache/CacheManager.java
  scm-webapp/src/main/java/sonia/scm/cache/CacheConfigurationLoader.java
  scm-webapp/src/main/java/sonia/scm/cache/CacheConfigurations.java
  scm-webapp/src/main/java/sonia/scm/cache/DefaultCacheConfigurationLoader.java
  scm-webapp/src/main/java/sonia/scm/cache/GuavaCache.java
  scm-webapp/src/main/java/sonia/scm/cache/GuavaCacheConfigurationReader.java
  scm-webapp/src/main/java/sonia/scm/cache/GuavaCacheManager.java
  scm-webapp/src/main/java/sonia/scm/cache/GuavaCacheManagerConfiguration.java
  scm-webapp/src/main/java/sonia/scm/cache/GuavaCaches.java
  scm-webapp/src/test/java/sonia/scm/cache/GuavaConfigurationReaderTest.java
  scm-webapp/src/test/java/sonia/scm/repository/DefaultRepositoryManagerPerfTest.java
Labels: enhancement

#1556 Reenable SonarQube analysis for pull requests
  Jenkinsfile
Labels: bug

#1559 Enable refetch on focus
  scm-ui/ui-api/src/ApiProvider.tsx
  scm-ui/ui-webapp/src/repos/containers/RepositoryRoot.tsx
Labels: enhancement

#1561 Fire RepositoryImportHookEvent instead of PostReceiveRepositoryHookEvent
  scm-core/src/main/java/sonia/scm/repository/ImportRepositoryHookEvent.java
  scm-core/src/main/java/sonia/scm/repository/api/UnbundleCommandBuilder.java
  scm-core/src/main/java/sonia/scm/repository/spi/UnbundleCommandRequest.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitPullCommand.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitRepositoryHookEventFactory.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitUnbundleCommand.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/AbstractRemoteCommandTestBase.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitPostReceiveRepositoryHookEventFactoryTest.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitUnbundleCommandTest.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgPullCommand.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgRepositoryHookEventFactory.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgRepositoryServiceProvider.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgRepositoryServiceResolver.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgUnbundleCommand.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgPostReceiveRepositoryHookEventFactoryTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgUnbundleCommandTest.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/repository/spi/SvnRepositoryServiceProvider.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/repository/spi/SvnRepositoryServiceResolver.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/repository/spi/SvnUnbundleCommand.java
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/repository/spi/SvnUnbundleCommandTest.java
  scm-webapp/src/main/java/sonia/scm/importexport/FullScmRepositoryImporter.java
  scm-webapp/src/main/java/sonia/scm/importexport/ImportState.java
  scm-webapp/src/main/java/sonia/scm/importexport/RepositoryImportStep.java
  scm-webapp/src/test/java/sonia/scm/importexport/FullScmRepositoryImporterTest.java
Labels: enhancement
