Repository scm-manager/scm-manager, pull requests merged in 2021-05, with the labels that each got.

#1637 Feature/hg verifier error messages
  gradle/changelog/hg_verification_error_messages.yaml
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/api/v2/resources/HgConfigResource.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/HgRepositoryHandler.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/HgVerifier.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/api/v2/resources/HgConfigResourceTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/autoconfig/PosixAutoConfiguratorTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/HgVerifierTest.java
  scm-ui/ui-components/src/config/Configuration.tsx
Labels: enhancement

#1645 Fix flickering form elements on repository initialization
  gradle/changelog/flickering_repo_initializer.yaml
  scm-ui/ui-webapp/src/repos/components/form/RepositoryForm.tsx
Labels: bug

#1643 Show correct default branch in repository config
  gradle/changelog/wrong_default_branch_shown.yaml
  scm-plugins/scm-git-plugin/src/main/js/RepositoryConfig.tsx
Labels: bug

#1650 Fix sse for notifications behind nginx reverse proxy
  gradle/changelog/notifications_behind_nginx.yaml
  scm-core/src/main/java/sonia/scm/sse/SseResponse.java
  scm-test/src/main/java/sonia/scm/web/RestDispatcher.java
  scm-webapp/src/main/java/sonia/scm/api/rest/SseHeaderResponseFilter.java
  scm-webapp/src/main/java/sonia/scm/api/v2/CacheControlResponseFilter.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/NotificationResource.java
  scm-webapp/src/test/java/sonia/scm/api/rest/SseHeaderResponseFilterTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/CacheControlResponseFilterTest.java
Labels: bug

#1655 Chromatic
  Jenkinsfile
  scm-ui/build.gradle
  scm-ui/ui-components/package.json
  yarn.lock
Labels: enhancement

#1654 Add TrustManagerProvider
  gradle/changelog/trust_manager_provider.yaml
  scm-webapp/src/main/java/sonia/scm/lifecycle/modules/ScmServletModule.java
  scm-webapp/src/main/java/sonia/scm/net/SSLContextProvider.java
  scm-webapp/src/main/java/sonia/scm/net/TrustManagerProvider.java
  scm-webapp/src/test/java/sonia/scm/net/TrustManagerProviderTest.java
Labels: do not merge, enhancement

#1653 Add testing guide
  docs/en/development/testing-guide.md
Labels: documentation

#1652 Use correct syntax for config routes
  gradle/changelog/config_routes.yaml
  scm-ui/ui-components/src/config/ConfigurationBinder.tsx
Labels: bug

#1638 Implement api for extension point typings
  docs/en/development/ui-extensions.md
  gradle/changelog/extension-point-typings.yaml
  scm-plugins/scm-git-plugin/package.json
  scm-plugins/scm-hg-plugin/package.json
  scm-plugins/scm-legacy-plugin/package.json
  scm-plugins/scm-svn-plugin/package.json
  scm-ui/ui-api/package.json
  scm-ui/ui-api/src/repositories.ts
  scm-ui/ui-components/package.json
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/forms/FilterInput.tsx
  scm-ui/ui-extensions/package.json
  scm-ui/ui-extensions/src/binder.test.ts
  scm-ui/ui-extensions/src/binder.ts
  scm-ui/ui-extensions/src/index.ts
  scm-ui/ui-plugins/package.json
  scm-ui/ui-tests/package.json
  yarn.lock
Labels: enhancement

#1661 Update jgit to v5.11.1.202105131744-r-scm1
  scm-plugins/scm-git-plugin/build.gradle
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/GitConfig.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitWorkingCopyInitializer.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitModifyCommand_withEmptyRepositoryTest.java
Labels: dependencies, enhancement

#1671 fix create link so that its correctly highlighted
  scm-ui/ui-webapp/src/repos/containers/Overview.tsx
Labels: bug

#1673 Update guice to version 5.0.1
  build.gradle
  gradle/dependencies.gradle
  scm-core/build.gradle
Labels: bug, dependencies

#1670 Add installation documentation for Cloudogu EcoSystem
  docs/en/installation/ces.md
  docs/en/installation/index.md
Labels: documentation

#1674 New configuration form
  scm-ui/ui-api/src/configLink.test.ts
  scm-ui/ui-api/src/configLink.ts
  scm-ui/ui-api/src/index.ts
  scm-ui/ui-components/src/config/Configuration.tsx
  scm-ui/ui-components/src/config/ConfigurationForm.tsx
  scm-ui/ui-components/src/config/index.ts
Labels: enhancement
