Repository scm-manager/scm-manager, pull requests merged in 2021-11, with the labels that each got.

#1839 Read all errors with screen reader
  gradle/changelog/screenreader_errors.yaml
  scm-ui/ui-components/src/BackendErrorNotification.tsx
  scm-ui/ui-components/src/ErrorNotification.tsx
  scm-ui/ui-components/src/Notification.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-styles/public/index.html
  scm-webapp/src/main/resources/locales/de/plugins.json
  scm-webapp/src/main/resources/locales/en/plugins.json
  scm-webapp/src/main/resources/templates/error.mustache
  scm-webapp/src/main/resources/templates/too-old.mustache
Labels: enhancement

#1840 Add alternative text to controls to allow screen readers to read them aloud
  gradle/changelog/alt_tags.yaml
  scm-ui/ui-components/src/Breadcrumb.stories.tsx
  scm-ui/ui-components/src/Breadcrumb.tsx
  scm-ui/ui-components/src/CardColumn.stories.tsx
  scm-ui/ui-components/src/CardColumnGroup.tsx
  scm-ui/ui-components/src/CardColumnSmall.stories.tsx
  scm-ui/ui-components/src/ErrorBoundary.tsx
  scm-ui/ui-components/src/HelpIcon.tsx
  scm-ui/ui-components/src/Icon.tsx
  scm-ui/ui-components/src/SplitAndReplace.stories.tsx
  scm-ui/ui-components/src/SyntaxHighlighterRenderer.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/buttons/Button.tsx
  scm-ui/ui-components/src/buttons/OpenInFullscreenButton.tsx
  scm-ui/ui-components/src/layout/GroupEntry.stories.tsx
  scm-ui/ui-components/src/markdown/MarkdownHeadingRenderer.tsx
  scm-ui/ui-components/src/navigation/SecondaryNavigation.tsx
  scm-ui/ui-components/src/repos/CommitAuthor.tsx
  scm-ui/ui-components/src/repos/DiffButton.tsx
  scm-ui/ui-components/src/repos/DiffFile.tsx
  scm-ui/ui-components/src/repos/JumpToFileButton.tsx
  scm-ui/ui-components/src/repos/RepositoryEntryLink.tsx
  scm-ui/ui-components/src/table/SortIcon.tsx
  scm-ui/ui-webapp/public/locales/de/admin.json
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/de/groups.json
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/de/users.json
  scm-ui/ui-webapp/public/locales/en/admin.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/public/locales/en/groups.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/public/locales/en/users.json
  scm-ui/ui-webapp/src/admin/plugins/components/PluginEntry.tsx
  scm-ui/ui-webapp/src/components/InfoBox.tsx
  scm-ui/ui-webapp/src/containers/Notifications.tsx
  scm-ui/ui-webapp/src/groups/components/table/GroupMember.tsx
  scm-ui/ui-webapp/src/repos/codeSection/components/FileSearchButton.tsx
  scm-ui/ui-webapp/src/repos/codeSection/components/FileSearchResults.tsx
  scm-ui/ui-webapp/src/repos/codeSection/containers/FileSearch.tsx
  scm-ui/ui-webapp/src/repos/components/changesets/ChangesetDetails.tsx
  scm-ui/ui-webapp/src/repos/components/form/RepositoryFormSwitcher.tsx
  scm-ui/ui-webapp/src/repos/components/list/RepositoryGroupEntry.tsx
  scm-ui/ui-webapp/src/repos/permissions/components/DeletePermissionButton.tsx
  scm-ui/ui-webapp/src/repos/sources/components/FileTreeLeaf.tsx
  scm-ui/ui-webapp/src/repos/sources/components/content/FileButtonAddons.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Content.tsx
  scm-ui/ui-webapp/src/search/Syntax.tsx
  scm-ui/ui-webapp/src/users/components/apiKeys/ApiKeyCreatedModal.tsx
Labels: enhancement

#1843 Viewer for pdf files
  gradle/changelog/pdfviewer.yaml
  scm-ui/ui-components/src/PdfViewer.stories.tsx
  scm-ui/ui-components/src/PdfViewer.tsx
  scm-ui/ui-components/src/__resources__/doc.pdf
  scm-ui/ui-components/src/index.ts
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/src/repos/sources/containers/SourcesView.tsx
Labels: enhancement

#1848 Update to webpack v5
  gradle/changelog/concurrent_modification.yaml
  gradle/changelog/logout_endless_loop.yaml
  package.json
  scm-plugins/scm-git-plugin/package.json
  scm-plugins/scm-hg-plugin/package.json
  scm-plugins/scm-legacy-plugin/package.json
  scm-plugins/scm-svn-plugin/package.json
  scm-ui/ui-api/package.json
  scm-ui/ui-api/src/admin.ts
  scm-ui/ui-api/src/config.ts
  scm-ui/ui-api/src/plugins.ts
  scm-ui/ui-api/src/repository-roles.ts
  scm-ui/ui-api/src/sources.ts
  scm-ui/ui-components/.storybook/RemoveThemesPlugin.js
  scm-ui/ui-components/.storybook/main.js
  scm-ui/ui-components/package.json
  scm-ui/ui-components/src/repos/TokenizedDiffView.tsx
  scm-ui/ui-extensions/package.json
  scm-ui/ui-plugins/package.json
  scm-ui/ui-scripts/package.json
  scm-ui/ui-scripts/src/commands/serve.js
  scm-ui/ui-scripts/src/webpack.config.js
  scm-ui/ui-styles/package.json
  scm-ui/ui-styles/webpack.config.js
  scm-ui/ui-webapp/package.json
  scm-webapp/src/main/java/sonia/scm/ProxyPushStateDispatcher.java
  settings.gradle
  yarn.lock
Labels: enhancement

#1854 Fix git unit tests on machines which are not using master as init branch
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitMirrorCommandTest.java
Labels: bug

#1855 Add contact icon with "mail to" action to the repository overview
  gradle/changelog/repo_overview_contact.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/repos/RepositoryEntry.tsx
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
Labels: enhancement

#1856 Multipart form support for AdvancedHttpClient
  gradle/changelog/ahc_multipart.yaml
  scm-core/src/main/java/sonia/scm/net/ahc/AdvancedHttpRequestWithBody.java
  scm-core/src/main/java/sonia/scm/net/ahc/FormContentBuilder.java
  scm-core/src/test/java/sonia/scm/net/ahc/AdvancedHttpRequestWithBodyTest.java
  scm-core/src/test/java/sonia/scm/net/ahc/FormContentBuilderTest.java
Labels: enhancement

#1859 Add move to modify command
  gradle/changelog/modify_command_move.yaml
  scm-core/src/main/java/sonia/scm/repository/api/ModifyCommandBuilder.java
  scm-core/src/main/java/sonia/scm/repository/spi/ModifyCommand.java
  scm-core/src/main/java/sonia/scm/repository/spi/ModifyCommandRequest.java
  scm-core/src/main/java/sonia/scm/repository/spi/ModifyWorkerHelper.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitModifyCommand.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitModifyCommandTest.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitModifyCommandTestBase.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitModifyCommand_LFSTest.java
  scm-plugins/scm-git-plugin/src/test/resources/sonia/scm/repository/spi/scm-git-spi-move-test.zip
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgModifyCommandTest.java
  scm-plugins/scm-hg-plugin/src/test/resources/sonia/scm/repository/spi/scm-hg-spi-modify-test.zip
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/repository/spi/SvnModifyCommandTest.java
  scm-plugins/scm-svn-plugin/src/test/resources/sonia/scm/repository/spi/scm-svn-spi-modify-test.zip
Labels: enhancement

#1871 Keep whole lines for code highlighting in search
  gradle/changelog/search_highlighter.yaml
  scm-webapp/src/main/java/sonia/scm/search/LuceneHighlighter.java
  scm-webapp/src/main/java/sonia/scm/search/QueryResultFactory.java
  scm-webapp/src/test/java/sonia/scm/search/LuceneHighlighterTest.java
  scm-webapp/src/test/resources/sonia/scm/search/Button.tsx.txt
  scm-webapp/src/test/resources/sonia/scm/search/GameOfLife.java.txt
  scm-webapp/src/test/resources/sonia/scm/search/content.txt
Labels: enhancement

#1875 upgrade query-string dependency version
  scm-ui/ui-api/package.json
  scm-ui/ui-api/src/urls.ts
  scm-ui/ui-components/package.json
  scm-ui/ui-plugins/package.json
  scm-ui/ui-webapp/package.json
  yarn.lock
Labels: dependencies

#1869 Cleanup html structure
  gradle/changelog/cleanup_html.yaml
  scm-ui/ui-components/src/DateFromNow.tsx
  scm-ui/ui-components/src/DateShort.tsx
  scm-ui/ui-components/src/Icon.tsx
  scm-ui/ui-components/src/OverviewPageActions.tsx
  scm-ui/ui-components/src/Tooltip.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/forms/FilterInput.tsx
  scm-ui/ui-components/src/forms/Select.tsx
  scm-ui/ui-components/src/layout/Header.tsx
  scm-ui/ui-components/src/navigation/SecondaryNavigation.tsx
  scm-ui/ui-components/src/repos/RepositoryFlags.tsx
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/src/containers/NavigationBar.tsx
  scm-ui/ui-webapp/src/containers/OmniSearch.tsx
  scm-ui/ui-webapp/src/repos/components/list/RepositoryGroupEntry.tsx
  scm-ui/ui-webapp/src/repos/sources/components/FileIcon.tsx
  scm-ui/ui-webapp/src/users/components/table/UserRow.tsx
Labels: bug
