Repository scm-manager/scm-manager, pull requests merged in 2021-06, with the labels that each got.

#1677 Remove duplicated notification endpoints in openapi
  gradle/changelog/duplicate_notification_endpoints.yaml
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/NotificationResource.java
Labels: bug

#1678 Fix annotate overflow and doubled spacing in code views
  gradle/changelog/annotate_overflow.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/repos/annotate/Annotate.tsx
  scm-ui/ui-components/src/repos/annotate/AnnotateLine.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/SourcesView.tsx
Labels: bug

#1680 Show source code controls even if a file is not present
  gradle/changelog/file_not_found_controls.yaml
  scm-ui/ui-webapp/src/repos/sources/containers/Content.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Sources.tsx
Labels: bug

#1687 Update DefaultAccessTokenCookieIssuer.java
  scm-webapp/src/main/java/sonia/scm/security/DefaultAccessTokenCookieIssuer.java
Labels: documentation

#1691 Fix tag position for repos with fav star
  gradle/changelog/repository_tag_position.yaml
  scm-ui/ui-webapp/src/repos/containers/RepositoryRoot.tsx
Labels: bug

#1692 Add handling when duplicated branch part cannot be created
  gradle/changelog/create_invalid_branch_exception.yaml
  scm-core/src/main/java/sonia/scm/BranchAlreadyExistsException.java
  scm-test/src/main/java/sonia/scm/web/RestDispatcher.java
  scm-ui/ui-webapp/src/repos/branches/containers/CreateBranch.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/BranchRootResource.java
  scm-webapp/src/main/resources/locales/de/plugins.json
  scm-webapp/src/main/resources/locales/en/plugins.json
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/BranchRootResourceTest.java
Labels: bug

#1693 Harmonize FileInput component with styleguide
  gradle/changelog/file_input_component.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/forms/FileInput.stories.tsx
  scm-ui/ui-components/src/forms/FileInput.tsx
  scm-ui/ui-styles/src/scm.scss
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
Labels: bug

#1694 Add support for basic authentication with access token
  gradle/changelog/basic_auth_with_access_token.yaml
  scm-webapp/src/main/java/sonia/scm/web/BasicWebTokenGenerator.java
  scm-webapp/src/test/java/sonia/scm/web/BasicWebTokenGeneratorTest.java
Labels: enhancement

#1698 Uniform rendering of tooltips for repository badges
  gradle/changelog/repository_flags.yaml
  scm-ui/ui-components/src/CardColumn.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/repos/RepositoryEntry.tsx
  scm-ui/ui-components/src/repos/RepositoryFlag.tsx
  scm-ui/ui-webapp/src/repos/containers/RepositoryRoot.tsx
Labels: bug

#1696 Form elements that support react-hook-form can now be made read-only
  gradle/changelog/readonly_form_elements.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/forms/Checkbox.stories.tsx
  scm-ui/ui-components/src/forms/Checkbox.tsx
  scm-ui/ui-components/src/forms/InputField.stories.tsx
  scm-ui/ui-components/src/forms/InputField.tsx
  scm-ui/ui-components/src/forms/Radio.stories.tsx
  scm-ui/ui-components/src/forms/Radio.tsx
  scm-ui/ui-components/src/forms/Select.stories.tsx
  scm-ui/ui-components/src/forms/Select.tsx
  scm-ui/ui-components/src/forms/Textarea.stories.tsx
  scm-ui/ui-components/src/forms/Textarea.tsx
Labels: enhancement

#1701 Clear caches if gpg key was added or deleted
  gradle/changelog/invalidate_caches_for_gpg_keys.yaml
  scm-core/src/main/java/sonia/scm/repository/api/RepositoryServiceFactory.java
Labels: bug

#1700 Fix single tag deletion
  gradle/changelog/delete_tag_with_redirect.yaml
  scm-ui/ui-api/src/tags.test.ts
  scm-ui/ui-api/src/tags.ts
  scm-ui/ui-webapp/src/repos/tags/components/TagTable.tsx
Labels: bug, do not merge

#1704 Building forms documentation with react-hook-form
  docs/en/development/build-from-source.md
  docs/en/development/building-forms.md
  docs/en/development/testing-guide.md
  docs/en/navigation.yml
  gradle/changelog/react_hook_form_doc.yaml
Labels: documentation

#1708 implement react-query for all content views
  scm-ui/ui-api/src/annotations.ts
  scm-ui/ui-api/src/changesets.ts
  scm-ui/ui-api/src/contentType.ts
  scm-ui/ui-api/src/history.ts
  scm-ui/ui-api/src/index.ts
  scm-ui/ui-webapp/src/repos/sources/containers/AnnotateView.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Content.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/HistoryView.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Sources.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/SourcesView.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/contentType.test.ts
  scm-ui/ui-webapp/src/repos/sources/containers/history.test.ts
Labels: enhancement

#1709 Include cloudogu plugins to plugin center
  gradle/changelog/cloudogu_plugins.yaml
  scm-core/src/main/java/sonia/scm/plugin/AvailablePluginDescriptor.java
  scm-core/src/main/java/sonia/scm/plugin/PluginInformation.java
  scm-ui/ui-api/src/plugins.test.ts
  scm-ui/ui-types/src/Plugin.ts
  scm-ui/ui-webapp/public/locales/de/admin.json
  scm-ui/ui-webapp/public/locales/en/admin.json
  scm-ui/ui-webapp/src/admin/plugins/components/PluginEntry.tsx
  scm-ui/ui-webapp/src/admin/plugins/components/PluginGroupEntry.tsx
  scm-ui/ui-webapp/src/admin/plugins/components/PluginList.tsx
  scm-ui/ui-webapp/src/admin/plugins/components/PluginModal.tsx
  scm-ui/ui-webapp/src/admin/plugins/containers/PluginsOverview.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/AvailablePluginResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/PluginDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/PluginDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/PluginRootResource.java
  scm-webapp/src/main/java/sonia/scm/plugin/PluginCenterDto.java
  scm-webapp/src/main/java/sonia/scm/plugin/PluginCenterDtoMapper.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/PluginDtoMapperTest.java
  scm-webapp/src/test/java/sonia/scm/plugin/PluginCenterDtoMapperTest.java
  scm-webapp/src/test/java/sonia/scm/plugin/PluginTestHelper.java
Labels: enhancement

#1713 Prevent overwrite read only gpg keys
  gradle/changelog/prevent_overwrite_read_only_gpg_keys.yaml
  scm-webapp/src/main/java/sonia/scm/security/gpg/PublicKeyStore.java
  scm-webapp/src/test/java/sonia/scm/security/gpg/PublicKeyStoreTest.java
Labels: bug

#1711 implement react-query for edge-cases
  scm-ui/ui-api/src/apiKeys.ts
  scm-ui/ui-api/src/base.ts
  scm-ui/ui-api/src/branches.test.ts
  scm-ui/ui-api/src/branches.ts
  scm-ui/ui-api/src/fileContent.ts
  scm-ui/ui-api/src/import.ts
  scm-ui/ui-api/src/index.ts
  scm-ui/ui-api/src/links.test.ts
  scm-ui/ui-api/src/links.ts
  scm-ui/ui-api/src/permissions.ts
  scm-ui/ui-api/src/publicKeys.ts
  scm-ui/ui-api/src/repositories.ts
  scm-ui/ui-api/src/users.ts
  scm-ui/ui-components/src/forms/FileInput.tsx
  scm-ui/ui-components/src/forms/FileUpload.tsx
  scm-ui/ui-types/src/ApiKeys.ts
  scm-ui/ui-types/src/GlobalPermissions.ts
  scm-ui/ui-types/src/PublicKeys.ts
  scm-ui/ui-types/src/RepositoryPermissions.ts
  scm-ui/ui-types/src/index.ts
  scm-ui/ui-webapp/src/containers/ChangeUserPassword.tsx
  scm-ui/ui-webapp/src/containers/Profile.tsx
  scm-ui/ui-webapp/src/groups/containers/SingleGroup.tsx
  scm-ui/ui-webapp/src/permissions/components/SetGroupPermissions.tsx
  scm-ui/ui-webapp/src/permissions/components/SetPermissions.tsx
  scm-ui/ui-webapp/src/permissions/components/SetUserPermissions.tsx
  scm-ui/ui-webapp/src/permissions/components/handlePermissions.test.ts
  scm-ui/ui-webapp/src/repos/branches/containers/DeleteBranch.tsx
  scm-ui/ui-webapp/src/repos/components/ImportFromBundleForm.tsx
  scm-ui/ui-webapp/src/repos/components/ImportFullRepository.tsx
  scm-ui/ui-webapp/src/repos/components/ImportFullRepositoryForm.tsx
  scm-ui/ui-webapp/src/repos/components/ImportRepositoryFromBundle.tsx
  scm-ui/ui-webapp/src/repos/components/ImportRepositoryFromUrl.tsx
  scm-ui/ui-webapp/src/repos/containers/EditRepo.tsx
  scm-ui/ui-webapp/src/repos/containers/ImportRepository.tsx
  scm-ui/ui-webapp/src/repos/containers/RenameRepository.tsx
  scm-ui/ui-webapp/src/repos/containers/RepositoryDangerZone.tsx
  scm-ui/ui-webapp/src/repos/sources/components/content/MarkdownViewer.tsx
  scm-ui/ui-webapp/src/repos/sources/components/content/SourcecodeViewer.tsx
  scm-ui/ui-webapp/src/users/components/SetUserPassword.tsx
  scm-ui/ui-webapp/src/users/components/apiKeys/AddApiKey.tsx
  scm-ui/ui-webapp/src/users/components/apiKeys/ApiKeyCreatedModal.tsx
  scm-ui/ui-webapp/src/users/components/apiKeys/ApiKeyEntry.tsx
  scm-ui/ui-webapp/src/users/components/apiKeys/ApiKeyTable.tsx
  scm-ui/ui-webapp/src/users/components/apiKeys/SetApiKeys.tsx
  scm-ui/ui-webapp/src/users/components/publicKeys/AddPublicKey.tsx
  scm-ui/ui-webapp/src/users/components/publicKeys/PublicKeyEntry.tsx
  scm-ui/ui-webapp/src/users/components/publicKeys/PublicKeyTable.tsx
  scm-ui/ui-webapp/src/users/components/publicKeys/SetPublicKeys.tsx
  scm-ui/ui-webapp/src/users/containers/SingleUser.tsx
Labels: enhancement

#1715 Show last modified date on repository overview
  gradle/changelog/repo_overview_date.yaml
  scm-ui/ui-components/src/repos/RepositoryEntry.tsx
Labels: enhancement

#1714 Fixed missing update if content of diff changes
  gradle/changelog/diff_disable_refetch_on_focus.yaml
  gradle/changelog/diff_update_content.yaml
  scm-ui/ui-api/src/diff.ts
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/repos/Diff.stories.tsx
  scm-ui/ui-components/src/repos/Diff.tsx
  scm-ui/ui-components/src/repos/LoadingDiff.tsx
Labels: bug
