Repository scm-manager/scm-manager, pull requests merged in 2021-03, with the labels that each got.

#1562 Fix build warnings
  scm-core/src/main/java/sonia/scm/ScmConstraintViolationException.java
  scm-core/src/main/java/sonia/scm/ServletContainer.java
  scm-core/src/main/java/sonia/scm/config/ScmConfiguration.java
  scm-core/src/main/java/sonia/scm/filter/GZipFilterConfig.java
  scm-core/src/main/java/sonia/scm/io/ScmObjectInputStream.java
  scm-core/src/main/java/sonia/scm/net/ahc/AdvancedHttpClient.java
  scm-core/src/main/java/sonia/scm/net/ahc/ContentTransformer.java
  scm-core/src/main/java/sonia/scm/repository/AbstractRepositoryManager.java
  scm-core/src/main/java/sonia/scm/repository/Added.java
  scm-core/src/main/java/sonia/scm/repository/Copied.java
  scm-core/src/main/java/sonia/scm/repository/Modified.java
  scm-core/src/main/java/sonia/scm/repository/Removed.java
  scm-core/src/main/java/sonia/scm/repository/Renamed.java
  scm-core/src/main/java/sonia/scm/repository/RepositoryHookEvent.java
  scm-core/src/main/java/sonia/scm/repository/RepositoryManager.java
  scm-core/src/main/java/sonia/scm/repository/api/MergeCommandBuilder.java
  scm-core/src/main/java/sonia/scm/repository/work/SimpleWorkingCopyFactory.java
  scm-core/src/main/java/sonia/scm/security/SecuritySystem.java
  scm-core/src/main/java/sonia/scm/store/ExportableStore.java
  scm-core/src/main/java/sonia/scm/util/Archives.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/GitRepositoryConfigMapper.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/GitUtil.java
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/repository/spi/SvnLookupCommandTest.java
  scm-test/src/main/java/sonia/scm/repository/SimpleRepositoryHandlerTestBase.java
  scm-test/src/main/java/sonia/scm/repository/client/api/RepositoryClientFactory.java
  scm-test/src/main/java/sonia/scm/repository/client/spi/AddCommand.java
  scm-test/src/main/java/sonia/scm/repository/client/spi/RemoveCommand.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ApiKeyToApiKeyDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/BlameDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/BrowserResultToFileObjectDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/DefaultChangesetToChangesetDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/DiffResultDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/GroupDtoToGroupMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/IncomingRootResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/NamespacePermissionResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/PluginDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryDtoToRepositoryMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryExportInformationToDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryRoleToRepositoryRoleDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryToRepositoryDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ResteasyViolationExceptionToErrorDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ScmViolationExceptionToErrorDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/UserDtoToUserMapper.java
  scm-webapp/src/main/java/sonia/scm/plugin/PluginsInternal.java
  scm-webapp/src/main/java/sonia/scm/security/DefaultSecuritySystem.java
  scm-webapp/src/main/java/sonia/scm/template/MustacheTemplate.java
Labels: bug

#1566 Clarify that FileUpload component does not upload directly
  gradle/changelog/adjust_fileupload.yaml
  scm-ui/ui-components/src/forms/FileUpload.tsx
  scm-ui/ui-styles/public/index.html
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
Labels: bug

#1570 Upgrade to react 17.0.1
  scm-plugins/scm-git-plugin/package.json
  scm-plugins/scm-hg-plugin/package.json
  scm-plugins/scm-legacy-plugin/package.json
  scm-plugins/scm-svn-plugin/package.json
  scm-ui/ui-api/package.json
  scm-ui/ui-components/package.json
  scm-ui/ui-extensions/package.json
  scm-ui/ui-plugins/package.json
  scm-ui/ui-tests/enzyme.ts
  scm-ui/ui-tests/package.json
  scm-ui/ui-webapp/package.json
  yarn.lock
Labels: enhancement

#1574 Mark configuration files in debian package
  gradle/changelog/debian_conffiles.yaml
  scm-packaging/deb/build.gradle
  scm-packaging/rpm/build.gradle
Labels: bug

#1576 Add API for metrics based on Micrometer
  gradle/changelog/metrics_api.yaml
  gradle/dependencies.gradle
  scm-core/build.gradle
  scm-core/src/main/java/sonia/scm/metrics/MonitoringSystem.java
  scm-core/src/main/java/sonia/scm/metrics/ScrapeTarget.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/MetricsIndexEnricher.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/MetricsResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ResourceLinks.java
  scm-webapp/src/main/java/sonia/scm/lifecycle/modules/ScmServletModule.java
  scm-webapp/src/main/java/sonia/scm/metrics/MeterRegistryProvider.java
  scm-webapp/src/main/resources/META-INF/scm/permissions.xml
  scm-webapp/src/main/resources/locales/de/plugins.json
  scm-webapp/src/main/resources/locales/en/plugins.json
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/MetricsIndexEnricherTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/MetricsResourceTest.java
  scm-webapp/src/test/java/sonia/scm/metrics/MeterRegistryProviderTest.java
Labels: enhancement

#1579 Add repository-specific nonFastForwardDisallowed option
  docs/de/user/repo/assets/repository-settings-general-git.png
  docs/de/user/repo/settings.md
  docs/en/user/repo/assets/repository-settings-general-git.png
  docs/en/user/repo/assets/repository-settings-general-svn.png
  docs/en/user/repo/settings.md
  gradle/changelog/repository_fastforward.yaml
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/GitRepositoryConfigDto.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/GitRepositoryConfigResource.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/GitRepositoryConfigStoreProvider.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/UpdateGitRepositoryConfigDto.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/protocolcommand/git/BaseReceivePackFactory.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/protocolcommand/git/ScmReceivePackFactory.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/GitRepositoryConfig.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/web/GitReceivePackFactory.java
  scm-plugins/scm-git-plugin/src/main/js/RepositoryConfig.tsx
  scm-plugins/scm-git-plugin/src/main/resources/locales/de/plugins.json
  scm-plugins/scm-git-plugin/src/main/resources/locales/en/plugins.json
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/protocolcommand/git/BaseReceivePackFactoryTest.java
Labels: enhancement

#1585 Encode revision for extension points to fix breaking change
  gradle/changelog/revision_encoding.yaml
  scm-ui/ui-components/src/Breadcrumb.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Content.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/SourceExtensions.tsx
Labels: bug

#1588 Fix diff for mercurial and subversion
  gradle/changelog/fix_diff_for_hg_and_svn.yaml
  scm-ui/ui-api/src/diff.test.ts
  scm-ui/ui-api/src/diff.ts
Labels: bug

#1589 Fix navigate to detail after search
  gradle/changelog/navigate_after_search.yaml
  scm-ui/ui-api/src/urls.ts
  scm-ui/ui-components/src/OverviewPageActions.tsx
Labels: bug

#1592 Fix missing redirect after login
  gradle/changelog/flappy_login.yaml
  scm-ui/ui-api/package.json
  scm-ui/ui-api/src/apiclient.ts
  scm-ui/ui-api/src/errors.ts
  scm-ui/ui-api/src/login.ts
  scm-ui/ui-webapp/src/containers/Login.tsx
  scm-ui/ui-webapp/src/tokenExpired.ts
  yarn.lock
Labels: bug

#1586 Core metrics
  gradle/changelog/core_metrics.yaml
  scm-core/src/main/java/sonia/scm/metrics/Metrics.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/web/GitHookEventFacade.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/BindTransportProtocolRule.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/SimpleGitWorkingCopyFactoryTest.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/hooks/HookServer.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/hooks/HookServerTest.java
  scm-webapp/src/main/java/sonia/scm/admin/ReleaseFeedParser.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryExportResource.java
  scm-webapp/src/main/java/sonia/scm/metrics/HttpMetricsFilter.java
  scm-webapp/src/main/java/sonia/scm/metrics/MeterRegistryProvider.java
  scm-webapp/src/main/java/sonia/scm/metrics/RequestCategory.java
  scm-webapp/src/main/java/sonia/scm/metrics/RequestCategoryDetector.java
  scm-webapp/src/main/java/sonia/scm/repository/DefaultRepositoryManager.java
  scm-webapp/src/main/java/sonia/scm/repository/DefaultSyncAsyncExecutorProvider.java
  scm-webapp/src/main/java/sonia/scm/schedule/CronScheduler.java
  scm-webapp/src/main/java/sonia/scm/template/MustacheTemplateEngine.java
  scm-webapp/src/main/java/sonia/scm/web/cgi/DefaultCGIExecutorFactory.java
  scm-webapp/src/test/java/sonia/scm/admin/ReleaseFeedParserTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/RepositoryRootResourceTest.java
  scm-webapp/src/test/java/sonia/scm/metrics/HttpMetricsFilterTest.java
  scm-webapp/src/test/java/sonia/scm/metrics/RequestCategoryDetectorTest.java
  scm-webapp/src/test/java/sonia/scm/repository/DefaultRepositoryManagerTest.java
  scm-webapp/src/test/java/sonia/scm/schedule/CronSchedulerTest.java
  scm-webapp/src/test/java/sonia/scm/template/MustacheTemplateEngineTest.java
Labels: enhancement

#1596 external nav links now correctly collapse when used in a menu
  gradle/changelog/non-collapsing-external-nav-link.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/navigation/ExternalLink.tsx
  scm-ui/ui-components/src/navigation/ExternalNavLink.tsx
Labels: bug

#1598 Missing test dependencies
  scm-test/build.gradle
Labels: bug

#1597 Custom permission roles
  gradle/changelog/custom_permission_role.yaml
  scm-ui/ui-webapp/src/repos/permissions/components/RoleSelector.tsx
  scm-ui/ui-webapp/src/repos/permissions/containers/CreatePermissionForm.tsx
  scm-ui/ui-webapp/src/repos/permissions/containers/SinglePermission.tsx
Labels: enhancement

#1602 Fix repository create route from namespace overview page
  gradle/changelog/repo_create_route.yaml
  scm-ui/ui-components/src/OverviewPageActions.tsx
  scm-ui/ui-webapp/src/repos/containers/Overview.tsx
Labels: bug

#1595 Feature/authentication metrics
  gradle/changelog/authentication_metrics.yaml
  scm-core/src/main/java/sonia/scm/metrics/Metrics.java
  scm-plugins/scm-legacy-plugin/src/main/java/sonia/scm/legacy/LegacyRealm.java
  scm-plugins/scm-legacy-plugin/src/test/java/sonia/scm/legacy/LegacyRealmTest.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/AuthenticationResource.java
  scm-webapp/src/main/java/sonia/scm/metrics/AuthenticationMetrics.java
  scm-webapp/src/main/java/sonia/scm/security/AnonymousRealm.java
  scm-webapp/src/main/java/sonia/scm/security/BearerRealm.java
  scm-webapp/src/main/java/sonia/scm/security/DefaultRealm.java
  scm-webapp/src/main/java/sonia/scm/security/ScmAtLeastOneSuccessfulStrategy.java
  scm-webapp/src/main/java/sonia/scm/web/security/TokenRefreshFilter.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/AuthenticationResourceTest.java
  scm-webapp/src/test/java/sonia/scm/security/AnonymousRealmTest.java
  scm-webapp/src/test/java/sonia/scm/security/BearerRealmTest.java
  scm-webapp/src/test/java/sonia/scm/security/DefaultRealmTest.java
  scm-webapp/src/test/java/sonia/scm/security/ScmAtLeastOneSuccessfulStrategyTest.java
  scm-webapp/src/test/java/sonia/scm/web/security/TokenRefreshFilterTest.java
Labels: enhancement

#1591 Collect metrics over lifetime of working copies
  gradle/changelog/workingcopy_metrics.yaml
  scm-core/src/main/java/sonia/scm/metrics/Metrics.java
  scm-core/src/main/java/sonia/scm/repository/work/SimpleWorkingCopyFactory.java
  scm-core/src/test/java/sonia/scm/repository/work/SimpleWorkingCopyFactoryTest.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/SimpleGitWorkingCopyFactory.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitMergeCommandTest.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitMergeCommand_Conflict_Test.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitModifyCommandTestBase.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/SimpleGitWorkingCopyFactoryTest.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/SimpleHgWorkingCopyFactory.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgBranchCommandTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgModifyCommandTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgTagCommandTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/SimpleHgWorkingCopyFactoryTest.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/repository/spi/SimpleSvnWorkingCopyFactory.java
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/repository/spi/SimpleSvnWorkingCopyFactoryTest.java
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/repository/spi/SvnModifyCommandTest.java
Labels: enhancement

#1601 Metrics for events
  build-plugins/src/main/groovy/com/cloudogu/scm/JavaModulePlugin.groovy
  build.gradle
  gradle/changelog/event_metrics.yaml
  gradle/dependencies.gradle
  scm-test/src/main/java/sonia/scm/event/ScmTestEventBus.java
  scm-webapp/build.gradle
  scm-webapp/src/main/java/sonia/scm/event/LegmanScmEventBus.java
  scm-webapp/src/main/java/sonia/scm/metrics/MeterRegistryProvider.java
  scm-webapp/src/test/java/sonia/scm/event/LegmanScmEventBusTest.java
Labels: bug, enhancement

#1600 Feature/unicode groupname validation
  gradle/changelog/unicode_name_validation.yaml
  scm-core/src/main/java/sonia/scm/repository/Repository.java
  scm-core/src/main/java/sonia/scm/repository/spi/HttpScmProtocol.java
  scm-core/src/main/java/sonia/scm/util/ValidationUtil.java
  scm-core/src/test/java/sonia/scm/repository/spi/HttpScmProtocolTest.java
  scm-core/src/test/java/sonia/scm/util/ValidationUtilTest.java
  scm-core/src/test/java/sonia/scm/util/ValidationUtil_IllegalCharactersTest.java
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/forms/InputField.tsx
  scm-ui/ui-components/src/markdown/remarkChangesetShortLinkParser.ts
  scm-ui/ui-components/src/validation.test.ts
  scm-ui/ui-components/src/validation.ts
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/components/NamespaceAndNameFields.tsx
  scm-ui/ui-webapp/src/repos/components/form/repositoryValidation.ts
  scm-webapp/src/main/java/sonia/scm/repository/CustomNamespaceStrategy.java
  scm-webapp/src/main/java/sonia/scm/repository/UsernameNamespaceStrategy.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/GroupRootResourceTest.java
  scm-webapp/src/test/java/sonia/scm/repository/UsernameNamespaceStrategyTest.java
Labels: enhancement

#1605 Fix stacktrace in response for invalid url
  gradle/changelog/url_exception.yaml
  scm-webapp/src/main/java/sonia/scm/api/v2/JsonMarshallingResponseFilter.java
Labels: bug

#1606 Disable api keys
  gradle/changelog/api_keys_config.yaml
  scm-core/src/main/java/sonia/scm/config/ScmConfiguration.java
  scm-it/src/test/java/sonia/scm/it/utils/TestData.java
  scm-ui/ui-api/src/config.test.ts
  scm-ui/ui-types/src/Config.ts
  scm-ui/ui-webapp/public/locales/de/config.json
  scm-ui/ui-webapp/public/locales/en/config.json
  scm-ui/ui-webapp/src/admin/components/form/ConfigForm.tsx
  scm-ui/ui-webapp/src/admin/components/form/GeneralSettings.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ConfigDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/MeDtoFactory.java
  scm-webapp/src/main/java/sonia/scm/security/ApiKeyRealm.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/MeDtoFactoryTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/MeResourceTest.java
  scm-webapp/src/test/java/sonia/scm/security/ApiKeyRealmTest.java
Labels: enhancement

#1608 Fix repository overview for not existing namespace
  gradle/changelog/namespace_not_existing.yaml
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/containers/Overview.tsx
Labels: bug

#1604 Validate filepath and filename to prevent path traversal
  gradle/changelog/prevent_path_traversal.yaml
  scm-core/src/main/java/sonia/scm/repository/spi/ModifyWorkerHelper.java
  scm-core/src/main/java/sonia/scm/util/ValidationUtil.java
  scm-core/src/test/java/sonia/scm/repository/spi/ModifyWorkerHelperTest.java
  scm-core/src/test/java/sonia/scm/util/ValidationUtilTest.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitModifyCommand.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitModifyCommandTest.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgModifyCommand.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgModifyCommandTest.java
  scm-ui/ui-components/src/validation.test.ts
  scm-ui/ui-components/src/validation.ts
  scm-webapp/src/main/java/sonia/scm/ManagerDaoAdapter.java
Labels: bug

#1607 Improve error messages for invalid media types
  gradle/changelog/improve_invalid_media_type_error.yaml
  scm-webapp/src/main/java/sonia/scm/api/v2/InvalidAcceptHeaderFilter.java
  scm-webapp/src/main/java/sonia/scm/api/v2/ResponseFilterPriorities.java
  scm-webapp/src/test/java/sonia/scm/api/v2/InvalidAcceptHeaderFilterTest.java
Labels: enhancement

#1609 Add more system metrics
  gradle/changelog/system_metrics.yaml
  gradle/dependencies.gradle
  scm-webapp/build.gradle
  scm-webapp/src/main/java/sonia/scm/metrics/HttpMetricsFilter.java
  scm-webapp/src/main/java/sonia/scm/metrics/MeterRegistryProvider.java
Labels: enhancement
