Repository scm-manager/scm-manager, pull requests merged in 2022-10, with the labels that each got.

#2128 Fix navbar at the top of the page
  gradle/changelog/fixted_navbar.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/layout/Header.tsx
  scm-ui/ui-components/src/navigation/SecondaryNavigation.tsx
  scm-ui/ui-styles/src/components/_main.scss
  scm-ui/ui-webapp/src/containers/App.tsx
  scm-ui/ui-webapp/src/containers/NavigationBar.tsx
Labels: enhancement

#2129 Add keyboard shortcuts documentation
  docs/de/navigation.yml
  docs/de/user/shortcuts/index.md
  docs/en/navigation.yml
  docs/en/user/shortcuts/index.md
  gradle/changelog/shortcuts_docs.yaml
  scm-ui/ui-webapp/package.json
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/containers/App.tsx
  scm-ui/ui-webapp/src/containers/Index.tsx
  scm-ui/ui-webapp/src/containers/OmniSearch.tsx
  scm-ui/ui-webapp/src/repos/containers/RepositoryRoot.tsx
  scm-ui/ui-webapp/src/shortcuts/ShortcutDocsModal.tsx
  scm-ui/ui-webapp/src/shortcuts/splitKeyCombination.test.ts
  scm-ui/ui-webapp/src/shortcuts/splitKeyCombination.ts
  scm-ui/ui-webapp/src/shortcuts/useShortcut.ts
  scm-ui/ui-webapp/src/shortcuts/useShortcutDocs.tsx
  yarn.lock
Labels: documentation, enhancement

#2138 Resolve plugin installation conflict
  gradle/changelog/plugin_installation_conflict.yaml
  scm-webapp/src/main/java/sonia/scm/plugin/DefaultPluginManager.java
  scm-webapp/src/test/java/sonia/scm/plugin/DefaultPluginManagerTest.java
Labels: bug

#2135 improve visibility of shortcut keys in the documentation by adding a contrasting border
  scm-ui/ui-webapp/src/shortcuts/ShortcutDocsModal.tsx
Labels: documentation

#2141 Git diff request correctly throws NotFoundException if target revision is non-existent
  gradle/changelog/diff_handle_deleted_target_branch.yaml
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/Differ.java
Labels: bug

#2143 Prevent concurrent access during Copy-on-Write
  gradle/changelog/copy_on_write.yaml
  scm-dao-xml/src/main/java/sonia/scm/store/CopyOnWrite.java
Labels: bug
