Repository scm-manager/scm-manager, pull requests merged in 2022-06, with the labels that each got.

#2051 Add api to overwrite content type resolver
  gradle/changelog/contentTypeResolverExtension.yaml
  scm-core/src/main/java/sonia/scm/io/ContentTypeResolverExtension.java
  scm-ui/ui-webapp/src/repos/sources/containers/SourcesView.tsx
  scm-webapp/src/main/java/sonia/scm/io/DefaultContentTypeResolver.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/ContentResourceTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/DiffResultToDiffResultDtoMapperTest.java
  scm-webapp/src/test/java/sonia/scm/io/DefaultContentTypeResolverTest.java
Labels: enhancement

#2057 Missing profile link in footer
  gradle/changelog/add_profile_link.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/layout/Footer.tsx
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
Labels: bug

#2058 Remove superfluous user theme link properties
  gradle/changelog/theme_nav_item.yaml
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/src/containers/Profile.tsx
Labels: bug

#2060 Arrow icon of secondary navigation is inconsistent
  gradle/changelog/secondary_nav_toogle_icon.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/navigation/SecondaryNavigation.tsx
Labels: bug

#2056 Calling search results without parameters
  gradle/changelog/empty_search.yaml
  scm-ui/ui-api/src/search.ts
Labels: bug

#2064 Remove branch validation on overview
  gradle/changelog/branch_overview_validation.yaml
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/BranchDetailsResource.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/BranchDetailsResourceTest.java
Labels: bug

#2068 Prevent corrupt lfs files during transfer
  gradle/changelog/lfs_corrupt_files.yaml
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/web/lfs/servlet/ScmFileTransferServlet.java
Labels: bug

#2076 allow card columns to omit the link
  gradle/changelog/linkless_card_column.yaml
  scm-ui/ui-components/src/CardColumnSmall.stories.tsx
  scm-ui/ui-components/src/CardColumnSmall.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
Labels: enhancement

#2078 add dependency check
  package.json
  scm-ui/build.gradle
  scm-ui/ui-syntaxhighlighting/package.json
  scm-ui/ui-text/package.json
  turbo.json
  yarn.lock
Labels: dependencies
