Repository scm-manager/scm-manager, pull requests merged in 2022-02, with the labels that each got.

#1922 Enable Gradle dependency locking
  README.md
  build.gradle
  gradle.lockfile
  gradle/wrapper/gradle-wrapper.properties
  scm-annotation-processor/gradle.lockfile
  scm-annotations/gradle.lockfile
  scm-core/gradle.lockfile
  scm-dao-xml/gradle.lockfile
  scm-it/gradle.lockfile
  scm-plugins/scm-git-plugin/gradle.lockfile
  scm-plugins/scm-hg-plugin/gradle.lockfile
  scm-plugins/scm-integration-test-plugin/gradle.lockfile
  scm-plugins/scm-legacy-plugin/gradle.lockfile
  scm-plugins/scm-svn-plugin/gradle.lockfile
  scm-server/gradle.lockfile
  scm-test/gradle.lockfile
  scm-ui/gradle.lockfile
  scm-webapp/gradle.lockfile
Labels: enhancement, dependencies

#1942 Update vulnerable version of cron-utils
  gradle/dependencies.gradle
  scm-it/gradle.lockfile
  scm-plugins/scm-git-plugin/gradle.lockfile
  scm-plugins/scm-hg-plugin/gradle.lockfile
  scm-plugins/scm-integration-test-plugin/gradle.lockfile
  scm-plugins/scm-legacy-plugin/gradle.lockfile
  scm-plugins/scm-svn-plugin/gradle.lockfile
  scm-webapp/gradle.lockfile
  scm-webapp/src/test/java/sonia/scm/web/i18n/I18nServletTest.java
Labels: bug, dependencies

#1941 Do not fail on error 502 during restart actions
  gradle/changelog/restart_bad_gateway.yaml
  scm-ui/ui-api/src/apiclient.test.ts
  scm-ui/ui-api/src/apiclient.ts
  scm-ui/ui-api/src/errors.ts
  scm-ui/ui-api/src/plugins.ts
Labels: bug

#1944 Add secondary color gradations to styleguide
  gradle/changelog/highcontrast_colors_styleguide.yaml
  scm-ui/ui-styles/public/_styleguide.html
Labels: enhancement

#1962 convert cucumber tests to standard cypress with typescript
  scm-ui/e2e-tests/cypress/integration/anonymous_mode_disabled.feature
  scm-ui/e2e-tests/cypress/integration/anonymous_mode_disabled_spec.ts
  scm-ui/e2e-tests/cypress/integration/anonymous_mode_full.feature
  scm-ui/e2e-tests/cypress/integration/anonymous_mode_full_spec.ts
  scm-ui/e2e-tests/cypress/integration/anonymous_mode_protocol_only.feature
  scm-ui/e2e-tests/cypress/integration/anonymous_mode_protocol_only_spec.ts
  scm-ui/e2e-tests/cypress/integration/repository_code_filesearch.feature
  scm-ui/e2e-tests/cypress/integration/repository_code_filesearch_spec.ts
  scm-ui/e2e-tests/cypress/plugins/index.ts
  scm-ui/e2e-tests/cypress/support/commands/index.ts
  scm-ui/e2e-tests/cypress/support/index.ts
  scm-ui/e2e-tests/cypress/tsconfig.json
  scm-ui/e2e-tests/package.json
Labels: enhancement
