Repository scm-manager/scm-manager, pull requests merged in 2022-01, with the labels that each got.

#1907 Make breadcrumb not clickable
  gradle/changelog/breadcrumb_not_clickable.yaml
  scm-ui/ui-components/src/Breadcrumb.stories.tsx
  scm-ui/ui-components/src/Breadcrumb.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
Labels: enhancement

#1908 Disable repository types
  gradle/changelog/disable_repository_types.yaml
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/GitConfigDto.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/GitConfigToGitConfigDtoMapper.java
  scm-plugins/scm-git-plugin/src/main/js/GitGlobalConfiguration.tsx
  scm-plugins/scm-git-plugin/src/main/resources/locales/de/plugins.json
  scm-plugins/scm-git-plugin/src/main/resources/locales/en/plugins.json
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/api/v2/resources/GitConfigToGitConfigDtoMapperTest.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/api/v2/resources/HgGlobalConfigToHgGlobalConfigDtoMapper.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/api/v2/resources/HgGlobalGlobalConfigDto.java
  scm-plugins/scm-hg-plugin/src/main/js/HgConfigurationForm.tsx
  scm-plugins/scm-hg-plugin/src/main/resources/locales/de/plugins.json
  scm-plugins/scm-hg-plugin/src/main/resources/locales/en/plugins.json
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/api/v2/resources/HgConfigResourceTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/api/v2/resources/HgGlobalConfigToHgGlobalConfigDtoMapperTest.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/api/v2/resources/SvnConfigDto.java
  scm-plugins/scm-svn-plugin/src/main/java/sonia/scm/api/v2/resources/SvnConfigToSvnConfigDtoMapper.java
  scm-plugins/scm-svn-plugin/src/main/js/SvnConfigurationForm.tsx
  scm-plugins/scm-svn-plugin/src/main/resources/locales/de/plugins.json
  scm-plugins/scm-svn-plugin/src/main/resources/locales/en/plugins.json
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/api/v2/resources/SvnConfigResourceTest.java
  scm-plugins/scm-svn-plugin/src/test/java/sonia/scm/api/v2/resources/SvnConfigToSvnConfigDtoMapperTest.java
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/containers/CreateRepositoryRoot.tsx
Labels: enhancement

#1910 Minor adjustments regarding high contrast mode
  gradle/changelog/high_contrast_findings.yaml
  scm-ui/ui-components/src/Breadcrumb.tsx
  scm-ui/ui-components/src/Logo.stories.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/repos/annotate/AnnotatePopover.tsx
  scm-ui/ui-styles/src/components/_main.scss
  scm-ui/ui-styles/src/highcontrast.scss
  scm-ui/ui-styles/src/light.scss
  scm-ui/ui-webapp/src/admin/plugins/components/PluginEntry.tsx
  scm-ui/ui-webapp/src/components/LoginForm.tsx
  scm-ui/ui-webapp/src/containers/OmniSearch.tsx
  scm-ui/ui-webapp/src/repos/codeSection/containers/FileSearch.tsx
Labels: enhancement

#1915 Update installation instructions
  docs/en/installation/debian.md
  docs/en/installation/osx.md
  docs/en/installation/redhat.md
  docs/en/installation/unix.md
  docs/en/installation/windows.md
Labels: documentation

#1923 Encrypt myCloudogu refresh token on file system
  gradle/changelog/encrypt_myc_token.yaml
  scm-webapp/src/main/java/sonia/scm/plugin/PluginCenterAuthenticator.java
  scm-webapp/src/main/java/sonia/scm/update/plugin/PluginCenterAuthenticationUpdateStep.java
  scm-webapp/src/test/java/sonia/scm/update/plugin/PluginCenterAuthentiationUpdateStepTest.java
Labels: bug

#1920 Compare branches, tags and revisions
  docs/de/user/repo/assets/repository-compare-view.png
  docs/de/user/repo/compare.md
  docs/de/user/repo/index.md
  docs/en/user/repo/assets/repository-compare-view.png
  docs/en/user/repo/compare.md
  docs/en/user/repo/index.md
  gradle/changelog/compare.yaml
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/api/v2/resources/RepositoryLinkEnricher.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/GitUtil.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitLogComputer.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/api/v2/resources/RepositoryLinkEnricherTest.java
  scm-plugins/scm-git-plugin/src/test/java/sonia/scm/repository/spi/GitDiffCommandWithTagsTest.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgDiffCommand.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgLogCommand.java
  scm-plugins/scm-hg-plugin/src/main/java/sonia/scm/repository/spi/HgRepositoryServiceProvider.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgDiffCommandTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgLogCommandAncestorTest.java
  scm-plugins/scm-hg-plugin/src/test/java/sonia/scm/repository/spi/HgLogCommandTest.java
  scm-ui/ui-api/src/compare.ts
  scm-ui/ui-api/src/index.ts
  scm-ui/ui-styles/public/_styleguide.html
  scm-ui/ui-styles/src/highcontrast.scss
  scm-ui/ui-styles/src/light.scss
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/branches/components/BranchDetail.tsx
  scm-ui/ui-webapp/src/repos/codeSection/components/CodeActionBar.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareLink.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareRoot.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareSelectBar.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareSelector.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareSelectorList.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareSelectorListEntry.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareTabs.tsx
  scm-ui/ui-webapp/src/repos/compare/CompareView.tsx
  scm-ui/ui-webapp/src/repos/compare/IncomingChangesets.tsx
  scm-ui/ui-webapp/src/repos/containers/Changesets.tsx
  scm-ui/ui-webapp/src/repos/containers/ChangesetsRoot.tsx
  scm-ui/ui-webapp/src/repos/containers/RepositoryRoot.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Sources.tsx
  scm-ui/ui-webapp/src/repos/tags/components/TagDetail.tsx
Labels: enhancement

#1925 Improve modal accessibility
  gradle/changelog/modal-focus.yaml
  scm-ui/ui-components/.storybook/main.js
  scm-ui/ui-components/package.json
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/buttons/Button.tsx
  scm-ui/ui-components/src/forms/PasswordConfirmation.tsx
  scm-ui/ui-components/src/modals/ConfirmAlert.stories.tsx
  scm-ui/ui-components/src/modals/ConfirmAlert.tsx
  scm-ui/ui-components/src/modals/CreateTagModal.tsx
  scm-ui/ui-components/src/modals/FullscreenModal.tsx
  scm-ui/ui-components/src/modals/Modal.stories.tsx
  scm-ui/ui-components/src/modals/Modal.tsx
  scm-ui/ui-components/src/useTrapFocus.ts
  scm-ui/ui-styles/src/components/_main.scss
  scm-ui/ui-webapp/src/admin/plugins/components/PluginActionModal.tsx
  scm-ui/ui-webapp/src/admin/plugins/components/PluginModal.tsx
  scm-ui/ui-webapp/src/admin/roles/containers/DeleteRepositoryRole.tsx
  scm-ui/ui-webapp/src/components/HeaderDropDown.tsx
  scm-ui/ui-webapp/src/groups/containers/DeleteGroup.tsx
  scm-ui/ui-webapp/src/permissions/components/PermissionCheckbox.tsx
  scm-ui/ui-webapp/src/repos/branches/components/BranchCommitDateCommitter.tsx
  scm-ui/ui-webapp/src/repos/branches/components/BranchTable.tsx
  scm-ui/ui-webapp/src/repos/branches/containers/DeleteBranch.tsx
  scm-ui/ui-webapp/src/repos/components/NamespaceAndNameFields.tsx
  scm-ui/ui-webapp/src/repos/components/changesets/CreateTagModal.tsx
  scm-ui/ui-webapp/src/repos/containers/ArchiveRepo.tsx
  scm-ui/ui-webapp/src/repos/containers/DeleteRepo.tsx
  scm-ui/ui-webapp/src/repos/containers/RenameRepository.tsx
  scm-ui/ui-webapp/src/repos/containers/UnarchiveRepo.tsx
  scm-ui/ui-webapp/src/repos/permissions/components/DeletePermissionButton.tsx
  scm-ui/ui-webapp/src/repos/permissions/containers/AdvancedPermissionsDialog.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/SourcesView.tsx
  scm-ui/ui-webapp/src/repos/tags/components/TagTable.tsx
  scm-ui/ui-webapp/src/repos/tags/container/DeleteTag.tsx
  scm-ui/ui-webapp/src/users/components/UserConverter.tsx
  scm-ui/ui-webapp/src/users/containers/DeleteUser.tsx
  yarn.lock
Labels: enhancement

#1935 Add myCloudogu data processing link
  docs/de/user/admin/plugins.md
  docs/en/user/admin/plugins.md
  gradle/changelog/dp_link.yaml
  scm-ui/ui-webapp/public/locales/de/admin.json
  scm-ui/ui-webapp/public/locales/en/admin.json
  scm-ui/ui-webapp/src/admin/plugins/components/MyCloudoguBanner.tsx
Labels: enhancement

#1939 Fix markdown toggle & only show source copy button on hover
  gradle/changelog/source-copy-and-markdown-toggle.yaml
  scm-ui/ui-components/src/SyntaxHighlighter.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/sources/components/content/SwitchableMarkdownViewer.tsx
Labels: bug, enhancement
