Repository scm-manager/scm-manager, pull requests merged in 2022-11, with the labels that each got.

#2145 Fix modal de-registration firing twice
  gradle/changelog/fix_modal_registration.yaml
  scm-ui/ui-components/src/modals/useRegisterModal.test.tsx
  scm-ui/ui-components/src/modals/useRegisterModal.ts
Labels: bug

#2146 Add keyboard navigation to repository overview list
  docs/de/user/shortcuts/index.md
  docs/en/user/shortcuts/index.md
  gradle/changelog/repo_overview_navigation.yaml
  scm-ui/ui-components/src/layout/GroupEntry.tsx
  scm-ui/ui-shortcuts/package.json
  scm-ui/ui-shortcuts/src/index.ts
  scm-ui/ui-shortcuts/src/iterator/keyboardIterator.test.tsx
  scm-ui/ui-shortcuts/src/iterator/keyboardIterator.tsx
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/src/repos/components/list/RepositoryList.tsx
  yarn.lock
Labels: enhancement

#2152 Add subrepository section in docs
  docs/de/user/repo/assets/create-repository.png
  docs/de/user/repo/assets/import-repository.png
  docs/de/user/repo/assets/repository-branch-detailView.png
  docs/de/user/repo/assets/repository-branches-overview.png
  docs/de/user/repo/assets/repository-code-filepathsearch.png
  docs/de/user/repo/assets/repository-code-sourcesView.png
  docs/de/user/repo/assets/repository-code-subrepository.png
  docs/de/user/repo/assets/repository-compare-view.png
  docs/de/user/repo/assets/repository-create-branch.png
  docs/de/user/repo/assets/repository-settings-general-export.png
  docs/de/user/repo/assets/repository-settings-general-git.png
  docs/de/user/repo/assets/repository-settings-general-health-check.png
  docs/de/user/repo/assets/repository-settings-permissionList.png
  docs/de/user/repo/assets/repository-settings-permissionOverview.png
  docs/de/user/repo/assets/repository-tag-detailView.png
  docs/de/user/repo/assets/repository-tags-overview.png
  docs/de/user/repo/code.md
  docs/en/user/repo/assets/create-repository.png
  docs/en/user/repo/assets/import-repository.png
  docs/en/user/repo/assets/repository-branch-detailView.png
  docs/en/user/repo/assets/repository-branches-overview.png
  docs/en/user/repo/assets/repository-code-filepathsearch.png
  docs/en/user/repo/assets/repository-code-sourcesView.png
  docs/en/user/repo/assets/repository-code-subrepository.png
  docs/en/user/repo/assets/repository-compare-view.png
  docs/en/user/repo/assets/repository-create-branch.png
  docs/en/user/repo/assets/repository-settings-general-export.png
  docs/en/user/repo/assets/repository-settings-general-git.png
  docs/en/user/repo/assets/repository-settings-general-health-check.png
  docs/en/user/repo/assets/repository-settings-permissionList.png
  docs/en/user/repo/assets/repository-settings-permissionOverview.png
  docs/en/user/repo/assets/repository-tag-detailView.png
  docs/en/user/repo/assets/repository-tags-overview.png
  docs/en/user/repo/code.md
  settings.gradle
Labels: documentation

#2153 Add keyboard navigation for users, groups, branches, tags, sources, changesets and plugins
  gradle/changelog/list_navigation.yaml
  scm-ui/ui-components/package.json
  scm-ui/ui-components/src/CardColumn.tsx
  scm-ui/ui-components/src/CardColumnGroup.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/buttons/Button.tsx
  scm-ui/ui-components/src/buttons/index.stories.tsx
  scm-ui/ui-components/src/modals/useRegisterModal.ts
  scm-ui/ui-components/src/repos/changesets/ChangesetButtonGroup.tsx
  scm-ui/ui-components/src/repos/changesets/ChangesetList.tsx
  scm-ui/ui-components/src/repos/changesets/ChangesetRow.tsx
  scm-ui/ui-components/src/repos/changesets/Changesets.stories.tsx
  scm-ui/ui-shortcuts/src/iterator/keyboardIterator.test.tsx
  scm-ui/ui-shortcuts/src/iterator/keyboardIterator.tsx
  scm-ui/ui-styles/src/components/_main.scss
  scm-ui/ui-webapp/src/admin/plugins/components/PluginEntry.tsx
  scm-ui/ui-webapp/src/admin/plugins/components/PluginList.tsx
  scm-ui/ui-webapp/src/groups/components/table/GroupRow.tsx
  scm-ui/ui-webapp/src/groups/components/table/GroupTable.tsx
  scm-ui/ui-webapp/src/repos/branches/components/BranchRow.tsx
  scm-ui/ui-webapp/src/repos/branches/containers/BranchTableWrapper.tsx
  scm-ui/ui-webapp/src/repos/sources/components/FileTree.tsx
  scm-ui/ui-webapp/src/repos/sources/components/FileTreeLeaf.tsx
  scm-ui/ui-webapp/src/repos/sources/components/content/FileLink.tsx
  scm-ui/ui-webapp/src/repos/tags/components/TagRow.tsx
  scm-ui/ui-webapp/src/repos/tags/components/TagTable.tsx
  scm-ui/ui-webapp/src/users/components/table/UserRow.tsx
  scm-ui/ui-webapp/src/users/components/table/UserTable.tsx
Labels: enhancement

#2142 Remove forced word break from markdown view
  gradle/changelog/markdown_table_header_wrap.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/markdown/LazyMarkdownView.tsx
Labels: bug

#2155 Implement sub-iterators for list navigation
  scm-ui/ui-components/src/modals/activeModalCountContext.ts
  scm-ui/ui-shortcuts/package.json
  scm-ui/ui-shortcuts/src/index.ts
  scm-ui/ui-shortcuts/src/iterator/callbackIterator.ts
  scm-ui/ui-shortcuts/src/iterator/keyboardIterator.test.tsx
  scm-ui/ui-shortcuts/src/iterator/keyboardIterator.tsx
  scm-ui/ui-webapp/src/repos/components/list/RepositoryList.tsx
  yarn.lock
Labels: enhancement

#2160 Implement focus for links and html buttons
  scm-ui/ui-styles/src/components/_main.scss
Labels: bug
