Repository scm-manager/scm-manager, pull requests merged in 2022-08, with the labels that each got.

#2101 Add api doc for cli and more
  scm-plugins/scm-legacy-plugin/src/main/java/sonia/scm/legacy/LegacyRepositoryService.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/CliResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryImportResource.java
Labels: documentation

#2097 Fix paging for too large page numbers
  gradle/changelog/fix_paging.yaml
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/markdown/MarkdownView.stories.tsx
  scm-ui/ui-webapp/src/admin/roles/containers/RepositoryRoles.tsx
  scm-ui/ui-webapp/src/groups/components/table/GroupTable.tsx
  scm-ui/ui-webapp/src/groups/containers/Groups.tsx
  scm-ui/ui-webapp/src/repos/containers/Changesets.tsx
  scm-ui/ui-webapp/src/repos/containers/ChangesetsRoot.tsx
  scm-ui/ui-webapp/src/search/Hits.tsx
  scm-ui/ui-webapp/src/search/Results.tsx
  scm-ui/ui-webapp/src/users/components/table/UserTable.tsx
  scm-ui/ui-webapp/src/users/containers/Users.tsx
Labels: bug

#2105 Fix broken compare view due to missing export
  gradle/changelog/fix_paging_compareview.yaml
  scm-ui/ui-webapp/src/repos/compare/CompareView.tsx
  scm-ui/ui-webapp/src/repos/compare/IncomingChangesets.tsx
  scm-ui/ui-webapp/src/repos/containers/Changesets.tsx
Labels: bug

#2104 Implement reindex mechanism for search
  gradle/changelog/reindex.yaml
  scm-core/src/main/java/sonia/scm/search/ReindexRepositoryEvent.java
  scm-ui/ui-api/src/repositories.ts
  scm-ui/ui-webapp/public/locales/de/repos.json
  scm-ui/ui-webapp/public/locales/en/repos.json
  scm-ui/ui-webapp/src/repos/components/Reindex.tsx
  scm-ui/ui-webapp/src/repos/containers/EditRepo.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryResource.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/RepositoryToRepositoryDtoMapper.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ResourceLinks.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/RepositoryRootResourceTest.java
  scm-webapp/src/test/java/sonia/scm/api/v2/resources/RepositoryToRepositoryDtoMapperTest.java
Labels: enhancement
