Repository scm-manager/scm-manager, pull requests merged in 2022-03, with the labels that each got.

#1968 update to newest version of integration-test-runner
  scm-ui/e2e-tests/cypress/plugins/index.ts
  scm-ui/e2e-tests/cypress/support/index.ts
  scm-ui/e2e-tests/cypress/tsconfig.json
  scm-ui/e2e-tests/package.json
  yarn.lock
Labels: dependencies

#1969 Introduce darkmode theme
  gradle/changelog/introduce_darkmode.yaml
  scm-ui/ui-components/.storybook/preview.js
  scm-ui/ui-components/src/DangerZone.tsx
  scm-ui/ui-components/src/SyntaxHighlighter.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
  scm-ui/ui-components/src/buttons/CreateButton.tsx
  scm-ui/ui-components/src/buttons/OpenInFullscreenButton.tsx
  scm-ui/ui-components/src/popover/Popover.tsx
  scm-ui/ui-components/src/repos/DiffButton.tsx
  scm-ui/ui-components/src/repos/JumpToFileButton.tsx
  scm-ui/ui-components/src/repos/annotate/AnnotatePopover.tsx
  scm-ui/ui-components/src/table/Table.stories.tsx
  scm-ui/ui-styles/public/_styleguide.html
  scm-ui/ui-styles/src/components/_main.scss
  scm-ui/ui-styles/src/dark.scss
  scm-ui/ui-styles/src/highcontrast.scss
  scm-ui/ui-styles/src/light.scss
  scm-ui/ui-styles/src/variables/_commons.scss
  scm-ui/ui-styles/src/variables/_derived.scss
  scm-ui/ui-webapp/public/images/blibSmallLightBackground.svg
  scm-ui/ui-webapp/public/index.mustache
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/src/admin/plugins/components/PluginBottomActions.tsx
  scm-ui/ui-webapp/src/components/HeaderButton.tsx
  scm-ui/ui-webapp/src/components/HeaderButtonContent.tsx
  scm-ui/ui-webapp/src/components/InfoBox.tsx
  scm-ui/ui-webapp/src/components/LoginForm.tsx
  scm-ui/ui-webapp/src/containers/Alerts.tsx
  scm-ui/ui-webapp/src/containers/NavigationBar.tsx
  scm-ui/ui-webapp/src/containers/Notifications.tsx
  scm-ui/ui-webapp/src/containers/Theme.tsx
  scm-ui/ui-webapp/src/repos/codeSection/components/CodeActionBar.tsx
  scm-ui/ui-webapp/src/repos/components/form/RepositoryFormSwitcher.tsx
  scm-ui/ui-webapp/src/repos/containers/ExportRepository.tsx
  scm-ui/ui-webapp/src/repos/sources/containers/Content.tsx
  scm-ui/ui-webapp/src/search/Syntax.tsx
Labels: enhancement

#1967 Add feedback form
  gradle/changelog/feedback.yaml
  scm-core/src/main/java/sonia/scm/config/ScmConfiguration.java
  scm-ui/ui-api/src/ApiProvider.test.tsx
  scm-ui/ui-api/src/LegacyContext.tsx
  scm-ui/ui-api/src/config.test.ts
  scm-ui/ui-api/src/config.ts
  scm-ui/ui-api/src/index.ts
  scm-ui/ui-types/src/Config.ts
  scm-ui/ui-types/src/IndexResources.ts
  scm-ui/ui-webapp/public/locales/de/commons.json
  scm-ui/ui-webapp/public/locales/de/config.json
  scm-ui/ui-webapp/public/locales/en/commons.json
  scm-ui/ui-webapp/public/locales/en/config.json
  scm-ui/ui-webapp/src/admin/components/form/ConfigForm.tsx
  scm-ui/ui-webapp/src/admin/components/form/GeneralSettings.tsx
  scm-ui/ui-webapp/src/containers/App.tsx
  scm-ui/ui-webapp/src/containers/Feedback.tsx
  scm-ui/ui-webapp/src/containers/Main.tsx
  scm-ui/ui-webapp/src/containers/Theme.tsx
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/ConfigDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/IndexDto.java
  scm-webapp/src/main/java/sonia/scm/api/v2/resources/IndexDtoGenerator.java
Labels: enhancement

#1973 Branch details invalidation
  gradle/changelog/branch_details_invalidation.yaml
  scm-ui/ui-api/src/branches.ts
Labels: bug

#1974 Not unique revisions on compare
  gradle/changelog/not_unique_compare.yaml
  scm-core/src/main/java/sonia/scm/NotUniqueRevisionException.java
  scm-plugins/scm-git-plugin/src/main/java/sonia/scm/repository/spi/GitDiffResultCommand.java
  scm-webapp/src/main/resources/locales/de/plugins.json
  scm-webapp/src/main/resources/locales/en/plugins.json
Labels: bug

#1977 Hide plugin dependencies on uninstall
  gradle/changelog/delete_plugin_dependencies.yaml
  scm-ui/ui-webapp/src/admin/plugins/components/PluginModal.tsx
Labels: bug

#1975 Handle ui test errors in Jenkins Pipeline
  Jenkinsfile
  gradle/changelog/jenkins_testing_stage.yaml
  package.json
  scm-ui/build.gradle
Labels: bug

#1980 fix certain plugin bundles being executed multiple times
  gradle/changelog/duplicate_module_execution.yaml
  scm-ui/ui-modules/src/index.ts
Labels: bug

#1984 Correct styling of syntax highlighter .section elements
  gradle/changelog/highlighter_styling.yaml
  scm-ui/ui-components/src/SyntaxHighlighterRenderer.tsx
  scm-ui/ui-components/src/__snapshots__/storyshots.test.ts.snap
Labels: bug
